addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
branches:
  only:
  - master
script:
- chmod +x .create_doxygen_and_deploy.sh
- "./.create_doxygen_and_deploy.sh"
