# Install dependencies
addons:
  apt:
    packages:
      - doxygen

after_success:
  - bash ./.create_doxygen_and_deploy.sh


# before_script:
#   - apt-get update -q && apt-get install -y -q doxygen
# pages:
#   script:
#   - doxygen doxygen.conf
#   only:
#   - master
