addons:
  apt:
    packages:
    - doxygen
    # - doxygen-doc
    # - doxygen-latex
    # - doxygen-gui
    # - graphviz

branches:
  only:
  - master

env:
  global:
    # - doocore_USER=Blablub
    - secure: pmTWJvp52mwlb+Mmoa+qgS4B5Ftob1pj6xpGzD3Xe+hoyc1pTOElAplbpH6Fnwzj7l/qal5d9zPDQd7lMkV0NwT4lAqemYbjNE6hvB61e2ZwK1lDgRV8QjsGdoiSYZMAn73UpwupSgw3in3GZ2ePYLvUFWYjypwMiFrXU4CfEM4Ujf8nZEtbnFR3+T5K1RZFfyMwT1Ix7Xu6VVl/HEes8/THw4zzzyr4AkqigoQhe8K1gl/LvwGUvzFVDqQBuBNvh59t4CzoYnResjc3RlMdKBT/LPRXLplUbEDcGvo+0HPUT/1zn+278tTsR9L9tWQvVHye9fwpwYSXJPCVVHTuBmPYDxdjcVs3oK8StmR2aWtyl8Qs/MfBAJ8zZn3j6mr1rOHR8fELge6IK2+WAxjbOUKcSeOFXouzxE/uIyAQAeUimB9Obf7Tlg39Q4Igqmpcpo4VT6GHmbifkTbtMS4hqkv9HCDyGVmzkvXG/xPUI9hnOy3iMRpCqowfr2aJiChcRC2YMApIYkTRjXKdK1IUuVGfXRoKhu4g5+1Xh2bSB6n9PrZusYg7YcxoXVzenKW4+Evs3hM8R4cdewt6mJsQKZ89viZM1TDfba0p+CnN6YvXDHHD31vqo/HuhCQXN1vlmPOtQwQ1smADuiMhSaJIQY0Wi9iFtAl59+sIGvGHqk8=

script:
- chmod +x .create_doxygen_and_deploy.sh
- "./.create_doxygen_and_deploy.sh"
