# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      # - doxygen-doc
      # - doxygen-latex
      # - doxygen-gui
      # - graphviz

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x .create_doxygen_and_deploy.sh
  - ./.create_doxygen_and_deploy.sh

# before_script:
#   - apt-get update -q && apt-get install -y -q doxygen
# pages:
#   script:
#   - doxygen doxygen.conf
#   only:
#   - master
