sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
branches:
  only:
  - master
# before_install:
  # - pwd
  # - doxygen doxygen.conf
  # - cd deploy_doxygen && docker build --build-arg DECRYPTED_KEY=id_rsa_doocore.enc --build-arg PROJECT=DooCore -t quick_doxygen_uploader .
script:
  # - pwd
  - cd .. && git clone https://github.com/alexbirne/deploy_doxygen.git
  - cd DooCore && doxygen doxygen.conf
  - mv html ../deploy_doxygen
  - cp id_rsa_doocore.enc ../deploy_doxygen
  - cd ../deploy_doxygen
  - export decrypted_key=$encrypted_26877b322e98_key
  - export encrypted_iv=$encrypted_26877b322e98_iv
  - docker build --build-arg DECRYPTED_KEY=id_rsa_doocore.enc -t quick_doxygen_uploader .
  - docker run -e DEPLOY_HOST=$DEPLOY_HOST -e DEPLOY_USER=$DEPLOY_USER -e DEPLOY_PATH=$DEPLOY_PATH -e DECRYPTED_SSH_KEY=id_rsa_doocore.enc quick_doxygen_uploader:latest
  # - cd deploy_doxygen && docker run -it -e DEPLOY_HOST=docs.e5.physik.tu-dortmund.de -e DEPLOY_USER=doocore -e DEPLOY_PATH=/services/doocore -e DECRYPTED_SSH_KEY=id_rsa_doocore
# - chmod +x .create_doxygen_and_deploy.sh
# - "./.create_doxygen_and_deploy.sh"
